languageCode = 'en-us'
title = 'ankalytics'

theme = 'saral'
pygmentsCodefences = true
pygmentsStyle = "doom-one"

[params]
    logoText = ""
    showHeroImage = true
    isBlogFocused = true
    math = true

[menu]
  [[menu.main]]
    name = "Обо мне"
    pre = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Статьи"
    pre = "pen-tool"
    url = "/posts/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]

